# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'NSOperation2' do
	pod 'Cosmos', '~> 1.2'
	pod 'Alamofire', '~> 3.3'
	pod 'SwiftyJSON', '~> 2.3'
end

