# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'NSOperation2' do
	pod 'TTGEmojiRate', '~> 0.1'
	pod 'Alamofire', '~> 3.3'
	pod 'AlamofireImage', '~> 2.4'
	pod 'SwiftyJSON', '~> 2.3'
end

